# Generated by Django 4.2.8 on 2023-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlockTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('number_of_connections', models.IntegerField(default=0)),
            ],
        ),
    ]
